// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.kgromov.protobuf.demo;

public interface HelloWorldRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kgromov.protobuf.demo.HelloWorldRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestId = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
