// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.kgromov.protobuf.demo;

public interface HelloWorldResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kgromov.protobuf.demo.HelloWorldResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
