// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.kgromov.protobuf.demo;

public final class HelloWorld {
  private HelloWorld() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kgromov_protobuf_demo_HelloWorldRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kgromov_protobuf_demo_HelloWorldRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kgromov_protobuf_demo_HelloWorldResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kgromov_protobuf_demo_HelloWorldResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021hello_world.proto\022\031com.kgromov.protobu" +
      "f.demo\"7\n\021HelloWorldRequest\022\021\n\trequestId" +
      "\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"$\n\022HelloWorldRes" +
      "ponse\022\016\n\006status\030\001 \001(\tB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_kgromov_protobuf_demo_HelloWorldRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kgromov_protobuf_demo_HelloWorldRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kgromov_protobuf_demo_HelloWorldRequest_descriptor,
        new java.lang.String[] { "RequestId", "Message", });
    internal_static_com_kgromov_protobuf_demo_HelloWorldResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kgromov_protobuf_demo_HelloWorldResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kgromov_protobuf_demo_HelloWorldResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
